"""Убрано указание партии в УИП по умолчанию

Revision ID: 1805bce1d329
Revises: a3b4c5d6e7f8
Create Date: 2026-08-14 13:46:00.964621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1805bce1d329'
down_revision: Union[str, Sequence[str], None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_templates', 'uip_include_batch',
               existing_type=sa.BOOLEAN(),
               comment='Включать партию в УИП',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'article',
               existing_type=sa.VARCHAR(length=50),
               comment='Артикул (текущий код 1С)',
               existing_comment='Текущий код 1С',
               existing_nullable=False)
    op.alter_column('products', 'gtin',
               existing_type=sa.VARCHAR(length=50),
               comment='GTIN групповой упаковки',
               existing_comment='GTIN',
               existing_nullable=False)
    op.alter_column('products', 'gtin_unit',
               existing_type=sa.VARCHAR(length=50),
               comment='GTIN единицы продукции (для УИП/DataMatrix)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'gtin_unit',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='GTIN единицы продукции (для УИП/DataMatrix)',
               existing_nullable=True)
    op.alter_column('products', 'gtin',
               existing_type=sa.VARCHAR(length=50),
               comment='GTIN',
               existing_comment='GTIN групповой упаковки',
               existing_nullable=False)
    op.alter_column('products', 'article',
               existing_type=sa.VARCHAR(length=50),
               comment='Текущий код 1С',
               existing_comment='Артикул (текущий код 1С)',
               existing_nullable=False)
    op.alter_column('code_templates', 'uip_include_batch',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Включать партию в УИП',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
