"""add table PrintJob

Revision ID: 36629821b5af
Revises: 95fb1c828ec9
Create Date: 2026-02-26 14:21:30.500943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36629821b5af'
down_revision: Union[str, Sequence[str], None] = '95fb1c828ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='id пользователя'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='id продукта'),
    sa.Column('printer_id', sa.UUID(), nullable=False, comment='id принтер'),
    sa.Column('template_id', sa.UUID(), nullable=False, comment='id шаблона'),
    sa.Column('batch_number', sa.String(length=50), nullable=False, comment='Номер партии'),
    sa.Column('marking_date', sa.Date(), nullable=False, comment='Дата маркировки'),
    sa.Column('expiration_date', sa.Date(), nullable=False, comment='Дата окончания срока годности'),
    sa.Column('first_box', sa.Integer(), nullable=False, comment='Номер первой коробки'),
    sa.Column('last_box', sa.Integer(), nullable=False, comment='Номер последней коробки'),
    sa.Column('boxes_count', sa.Integer(), nullable=False, comment='Количество коробок'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус печати (pending, processing, completed, failed, cancelled)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке'),
    sa.Column('printed_count', sa.Integer(), nullable=True, comment='Количество напечатанных этикеток'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата завершения'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['code_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Задания на печать этикеток'
    )
    op.create_index('ix_print_jobs_created_at', 'print_jobs', ['created_at'], unique=False)
    op.create_index('ix_print_jobs_user_status', 'print_jobs', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_print_jobs_user_status', table_name='print_jobs')
    op.drop_index('ix_print_jobs_created_at', table_name='print_jobs')
    op.drop_table('print_jobs')
    # ### end Alembic commands ###
