"""up max_lenght to 45 in Printer for row ip_address

Revision ID: 6acd694e7127
Revises: bfd9a6d5bfd3
Create Date: 2026-02-25 09:58:58.077299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acd694e7127'
down_revision: Union[str, Sequence[str], None] = 'bfd9a6d5bfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('printers', 'ip_address',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=45),
               existing_comment='IP-адрес',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('printers', 'ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=16),
               existing_comment='IP-адрес',
               existing_nullable=False)
    # ### end Alembic commands ###
