"""add table WorkshopUser

Revision ID: 95fb1c828ec9
Revises: 6acd694e7127
Create Date: 2026-02-26 13:10:56.398962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fb1c828ec9'
down_revision: Union[str, Sequence[str], None] = '6acd694e7127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lines', 'workshop_id',
               existing_type=sa.UUID(),
               comment='id цеха',
               existing_comment='UUID цеха',
               existing_nullable=False)
    op.alter_column('printers', 'line_id',
               existing_type=sa.UUID(),
               comment='id линии',
               existing_comment='UUID линии',
               existing_nullable=False)
    op.add_column('workshop_users', sa.Column('workshop_id', sa.UUID(), nullable=False, comment='id цеха'))
    op.add_column('workshop_users', sa.Column('line_id', sa.UUID(), nullable=True, comment='id линии'))
    op.add_column('workshop_users', sa.Column('role_in_workshop', sa.String(length=50), nullable=False, comment='Роль в цеху: master, operator, supervisor'))
    op.add_column('workshop_users', sa.Column('is_active', sa.Boolean(), nullable=False, comment='Доступ к цеху'))
    op.add_column('workshop_users', sa.Column('comment', sa.String(length=255), nullable=True, comment='Комментарий'))
    op.alter_column('workshop_users', 'user_id',
               existing_type=sa.UUID(),
               comment='id пользователя',
               existing_comment='id продукта',
               existing_nullable=False)
    op.create_index('ix_workshop_users_user_active', 'workshop_users', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_workshop_users_workshop_active', 'workshop_users', ['workshop_id', 'is_active'], unique=False)
    op.create_unique_constraint('uq_workshop_user', 'workshop_users', ['user_id', 'workshop_id'])
    op.drop_constraint(op.f('workshop_users_printer_id_fkey'), 'workshop_users', type_='foreignkey')
    op.drop_constraint(op.f('workshop_users_user_id_fkey'), 'workshop_users', type_='foreignkey')
    op.create_foreign_key(None, 'workshop_users', 'lines', ['line_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workshop_users', 'workshops', ['workshop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workshop_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'workshop_users',
        'Привязка пользователей к цехам',
        existing_comment='Пользователи цеха',
        schema=None
    )
    op.drop_column('workshop_users', 'printer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop_users', sa.Column('printer_id', sa.UUID(), autoincrement=False, nullable=False, comment='id принтера'))
    op.create_table_comment(
        'workshop_users',
        'Пользователи цеха',
        existing_comment='Привязка пользователей к цехам',
        schema=None
    )
    op.drop_constraint(None, 'workshop_users', type_='foreignkey')
    op.drop_constraint(None, 'workshop_users', type_='foreignkey')
    op.drop_constraint(None, 'workshop_users', type_='foreignkey')
    op.create_foreign_key(op.f('workshop_users_user_id_fkey'), 'workshop_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('workshop_users_printer_id_fkey'), 'workshop_users', 'printers', ['printer_id'], ['id'])
    op.drop_constraint('uq_workshop_user', 'workshop_users', type_='unique')
    op.drop_index('ix_workshop_users_workshop_active', table_name='workshop_users')
    op.drop_index('ix_workshop_users_user_active', table_name='workshop_users')
    op.alter_column('workshop_users', 'user_id',
               existing_type=sa.UUID(),
               comment='id продукта',
               existing_comment='id пользователя',
               existing_nullable=False)
    op.drop_column('workshop_users', 'comment')
    op.drop_column('workshop_users', 'is_active')
    op.drop_column('workshop_users', 'role_in_workshop')
    op.drop_column('workshop_users', 'line_id')
    op.drop_column('workshop_users', 'workshop_id')
    op.alter_column('printers', 'line_id',
               existing_type=sa.UUID(),
               comment='UUID линии',
               existing_comment='id линии',
               existing_nullable=False)
    op.alter_column('lines', 'workshop_id',
               existing_type=sa.UUID(),
               comment='UUID цеха',
               existing_comment='id цеха',
               existing_nullable=False)
    # ### end Alembic commands ###
