"""Initial schema

Revision ID: bfd9a6d5bfd3
Revises: 
Create Date: 2026-02-11 09:50:45.649866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd9a6d5bfd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('current_code_1c', sa.String(length=50), nullable=False, comment='Текущий код 1С'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование'),
    sa.Column('gtin', sa.String(length=50), nullable=False, comment='GTIN'),
    sa.Column('other_codes_1c', sa.Text(), nullable=True, comment='Другие коды 1C'),
    sa.Column('date_expiration', sa.Integer(), nullable=False, comment='Срок годности в днях'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_code_1c'),
    sa.UniqueConstraint('gtin'),
    comment='Продукты'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='Описание'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Админ'),
    sa.Column('is_editor', sa.Boolean(), nullable=True, comment='Редактирование'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата добавления'),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата редактирования'),
    sa.PrimaryKeyConstraint('id'),
    comment='Роли'
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('workshops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата добавления'),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата редактирования'),
    sa.PrimaryKeyConstraint('id'),
    comment='Цеха'
    )
    op.create_index(op.f('ix_workshops_name'), 'workshops', ['name'], unique=True)
    op.create_table('lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workshop_id', sa.UUID(), nullable=False, comment='UUID цеха'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименования'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата добавления'),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата редактирования'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Линии'
    )
    op.create_index(op.f('ix_lines_name'), 'lines', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False, comment='Логин'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Пароль'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='E-mail'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активен'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата добавления'),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата редактирования'),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='Пользователи'
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('printers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.UUID(), nullable=False, comment='UUID линии'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование'),
    sa.Column('ip_address', sa.String(length=16), nullable=False, comment='IP-адрес'),
    sa.Column('port_address', sa.Integer(), nullable=False, comment='Порт'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата добавления'),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата редактирования'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Принтеры'
    )
    op.create_index(op.f('ix_printers_ip_address'), 'printers', ['ip_address'], unique=True)
    op.create_index(op.f('ix_printers_name'), 'printers', ['name'], unique=True)
    op.create_index(op.f('ix_printers_port_address'), 'printers', ['port_address'], unique=False)
    op.create_table('code_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='id продукта'),
    sa.Column('printer_id', sa.UUID(), nullable=False, comment='id принтера'),
    sa.Column('print_code', sa.Text(), nullable=False, comment='Код шаблона'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активен'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата добавления'),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата редактирования'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Коды шаблонов'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_templates')
    op.drop_index(op.f('ix_printers_port_address'), table_name='printers')
    op.drop_index(op.f('ix_printers_name'), table_name='printers')
    op.drop_index(op.f('ix_printers_ip_address'), table_name='printers')
    op.drop_table('printers')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lines_name'), table_name='lines')
    op.drop_table('lines')
    op.drop_index(op.f('ix_workshops_name'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('products')
    # ### end Alembic commands ###
