"""Add cascade delete in table

Revision ID: cab6df366dc0
Revises: d0f1a83e977d
Create Date: 2026-03-13 17:58:14.690767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab6df366dc0'
down_revision: Union[str, Sequence[str], None] = 'd0f1a83e977d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('code_templates_printer_id_fkey'), 'code_templates', type_='foreignkey')
    op.drop_constraint(op.f('code_templates_product_id_fkey'), 'code_templates', type_='foreignkey')
    op.create_foreign_key(None, 'code_templates', 'printers', ['printer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'code_templates', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lines_workshop_id_fkey'), 'lines', type_='foreignkey')
    op.create_foreign_key(None, 'lines', 'workshops', ['workshop_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('printers_line_id_fkey'), 'printers', type_='foreignkey')
    op.create_foreign_key(None, 'printers', 'lines', ['line_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printers', type_='foreignkey')
    op.create_foreign_key(op.f('printers_line_id_fkey'), 'printers', 'lines', ['line_id'], ['id'])
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.create_foreign_key(op.f('lines_workshop_id_fkey'), 'lines', 'workshops', ['workshop_id'], ['id'])
    op.drop_constraint(None, 'code_templates', type_='foreignkey')
    op.drop_constraint(None, 'code_templates', type_='foreignkey')
    op.create_foreign_key(op.f('code_templates_product_id_fkey'), 'code_templates', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('code_templates_printer_id_fkey'), 'code_templates', 'printers', ['printer_id'], ['id'])
    # ### end Alembic commands ###
