"""Add cascade delete to print_jobs.template_id

Revision ID: d0f1a83e977d
Revises: 36629821b5af
Create Date: 2026-03-13 16:29:29.079302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f1a83e977d'
down_revision: Union[str, Sequence[str], None] = '36629821b5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('print_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус печати (pending, processing, pause, completed, failed, cancelled)',
               existing_comment='Статус печати (pending, processing, completed, failed, cancelled)',
               existing_nullable=False)
    op.drop_constraint(op.f('print_jobs_printer_id_fkey'), 'print_jobs', type_='foreignkey')
    op.drop_constraint(op.f('print_jobs_product_id_fkey'), 'print_jobs', type_='foreignkey')
    op.drop_constraint(op.f('print_jobs_template_id_fkey'), 'print_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'print_jobs', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'print_jobs', 'code_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'print_jobs', 'printers', ['printer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'print_jobs', type_='foreignkey')
    op.drop_constraint(None, 'print_jobs', type_='foreignkey')
    op.drop_constraint(None, 'print_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('print_jobs_template_id_fkey'), 'print_jobs', 'code_templates', ['template_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('print_jobs_product_id_fkey'), 'print_jobs', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('print_jobs_printer_id_fkey'), 'print_jobs', 'printers', ['printer_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('print_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус печати (pending, processing, completed, failed, cancelled)',
               existing_comment='Статус печати (pending, processing, pause, completed, failed, cancelled)',
               existing_nullable=False)
    # ### end Alembic commands ###
