"""Add cascade='all, delete-orphan' in all table

Revision ID: fe21ba439272
Revises: c9dd5dc70482
Create Date: 2026-03-13 18:15:49.694043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe21ba439272'
down_revision: Union[str, Sequence[str], None] = 'c9dd5dc70482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('print_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус печати',
               existing_comment='Статус печати (pending, processing, pause, completed, failed, cancelled)',
               existing_nullable=False)
    op.alter_column('workshop_users', 'role_in_workshop',
               existing_type=sa.VARCHAR(length=50),
               comment='Роль в цеху',
               existing_comment='Роль в цеху: master, operator, supervisor',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshop_users', 'role_in_workshop',
               existing_type=sa.VARCHAR(length=50),
               comment='Роль в цеху: master, operator, supervisor',
               existing_comment='Роль в цеху',
               existing_nullable=False)
    op.alter_column('print_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус печати (pending, processing, pause, completed, failed, cancelled)',
               existing_comment='Статус печати',
               existing_nullable=False)
    # ### end Alembic commands ###
